# Generated by Django 4.2.29 on 2026-04-02 07:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount. Must be greater than 0.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('record_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], help_text='Whether this is an income or expense record.', max_length=7)),
                ('category', models.CharField(choices=[('SALARY', 'Salary'), ('FREELANCE', 'Freelance'), ('INVESTMENT', 'Investment'), ('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('FOOD', 'Food'), ('TRANSPORT', 'Transport'), ('HEALTHCARE', 'Healthcare'), ('ENTERTAINMENT', 'Entertainment'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], help_text='Category of the financial record.', max_length=15)),
                ('date', models.DateField(help_text='Date of the transaction.')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about the transaction.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag. True = record is "deleted" but preserved.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'financial_records',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
