# Generated by Django 4.2.29 on 2026-04-02 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record. Preserved even if user is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['record_type'], name='idx_record_type'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['category'], name='idx_category'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['date'], name='idx_date'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['is_deleted'], name='idx_is_deleted'),
        ),
    ]
