# Generated by Django 5.2.12 on 2026-04-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='category',
            field=models.CharField(choices=[('OFFICE_RENT', 'Office Rent'), ('SALARIES', 'Salaries'), ('CONTRACTOR_FEES', 'Contractor Fees'), ('EMPLOYEE_BENEFITS', 'Employee Benefits'), ('RECRUITMENT', 'Recruitment'), ('SOFTWARE_TOOLS', 'Software & Tools'), ('AI_TOOLS', 'AI Tools'), ('CLOUD_INFRASTRUCTURE', 'Cloud Infrastructure'), ('EQUIPMENT_HARDWARE', 'Equipment & Hardware'), ('UTILITIES_INTERNET', 'Utilities & Internet'), ('ADVERTISING_MARKETING', 'Advertising & Marketing'), ('FOOD_BEVERAGES', 'Food & Beverages'), ('TRAVEL_TRANSPORT', 'Travel & Transport'), ('LEGAL_COMPLIANCE', 'Legal & Compliance'), ('OTHER_EXPENSE', 'Other Expense'), ('CLIENT_REVENUE', 'Client Revenue'), ('PRODUCT_SALES', 'Product Sales'), ('SUBSCRIPTION_REVENUE', 'Subscription Revenue'), ('CONSULTING', 'Consulting'), ('INVESTMENT_FUNDING', 'Investment & Funding'), ('INTEREST_INCOME', 'Interest Income'), ('GRANT_SUBSIDY', 'Grant & Subsidy'), ('OTHER_INCOME', 'Other Income')], help_text='Category of the financial record.', max_length=25),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag. True = record is preserved but hidden.'),
        ),
    ]
